<?php

/*
Template Name: DO NOT EDIT
This file is previously known as "functions.php".
This version is for necessary functions to run the options page 
for the end user.  Do not edit this file.
*/

$themeData = get_theme_data(TEMPLATEPATH . '/style.css');
$installedVersion = $themeData['Version'];
if(!$installedVersion) {
	$installedVersion = "unknown";
}

function oc_linky_love() { 
?>

        design by <a href="http://www.brassblogs.com">Brass Blogs</a><br />
        powered by <a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress</a>

<?php } 

$highlightColor = "#a3c5cc";

add_action('admin_head', 'inject_orange_crush_js');
add_action('activity_box_end', 'update_dashboard');

// widgets!
if ( function_exists('register_sidebars') )
	register_sidebar(array(
		'before_widget' => '<div id="%1$s" class="widget %2$s">',         // Removes <li>
		'after_widget' => '</div>',                                       // Removes </li>
		'before_title' => '<div class="title">',                          // Replaces <h2>
		'after_title' => '</div>',                                        // Replaces </h2>
	));


function widget_mytheme_search() {
?>
	 <div id="search">
		<form method="get" id="searchform" action="<?php bloginfo('home'); ?>">
                <div> <!-- for validation purposes -->
		<input type="text" name="s" id="s" value="search me!" />
		<input class="button" id="searchsubmit" type="image" value="&nbsp; &nbsp; &nbsp;" />
                </div> <!-- closing div tag for validation purposes -->
	  	</form>
    	        </div> <!-- closing #search -->

<?php
}

if ( function_exists('register_sidebar_widget') )
	register_sidebar_widget(__('Search'), 'widget_mytheme_search');

// end widget stuff

function update_dashboard() {
	global $installedVersion;
	
	echo "<h3>Orange Crush Updates</h3>\n";
	if(get_option('orange_crush_update_notification') == 'true') {
		echo "<script src=\"http://localhost/wordpress2.02/wp-content/themes/orange_crush/js/version.php?version=$installedVersion&verbose=true\" type=\"text/javascript\"></script>\n";
	} else {
		echo "<p>Update notification for the Orange Crush theme <a href=\"themes.php?page=functions.php\">is currently turned off</a>.</p>";
	}
}

function inject_orange_crush_js() {
	echo '<script src="' . get_bloginfo('template_directory') . '/js/prototype.js' .'" type="text/javascript"></script>';
	echo '<script src="' . get_bloginfo('template_directory') . '/js/scriptaculous.js' .'" type="text/javascript"></script>';
	echo '<script src="' . get_bloginfo('template_directory') . '/js/orange_crush.js' .'" type="text/javascript"></script>';
}

function orange_crushupdate() {
	global $wpdb, $user_ID;
	get_currentuserinfo();
	
	if ( !empty($_POST) ) {
		if($_POST['orange_crush_update_notification'] == 'Turn update notification off?') {
			update_option('orange_crush_update_notification', 'false');
		}	elseif($_POST['orange_crush_update_notification'] == 'Turn update notification on?') {
			update_option('orange_crush_update_notification', 'true');
		}
		
		if (isset($_POST['about_text'])) {
			$about = $_POST['about_text'];
			update_option('blurb', $about, '','');
		}
		if (isset($_POST['header_image'])) {
			$header = $_POST['header_image'];
			$header = @str_replace("-thumb", "", $header);
			update_option('orange_crush_header', $header, '','');
		}
		
		update_option('orange_crush_sidebar_pages', $_POST['sidebar']['pages']);
		update_option('orange_crush_sidebar_links', $_POST['sidebar']['links']);
		update_option('orange_crush_sidebar_comments', $_POST['sidebar']['comments']);
		update_option('orange_crush_sidebar_custom', $_POST['sidebar']['custom']);
		update_option('orange_crush_sidebar_onlyhome', $_POST['sidebar']['onlyhome']);
		
		update_option('orange_crush_display_tagline', $_POST['display_tagline']);
		update_option('orange_crush_hide_categories', $_POST['hide_categories']);
		update_option('orange_crush_centered_theme', $_POST['centered_theme']);
		update_option('orange_crush_swap_sides', $_POST['swap_sides']);
		update_option('orange_crush_asidescategory', $_POST['asides_category']);
		update_option('orange_crush_style', $_POST['alternate_style']);
		update_option('orange_crush_ajax_tags', $_POST['ajax_tags']);
		
		update_option('orange_crush_nav_pages', implode(',', $_POST['nav_pages']));
		
		if(in_array('about', $_POST['create_page'])) {
			if(!orange_crush_checkForStaticPage('About')) {
				orange_crush_createStaticPage('About', '', 'static.php');
			}
		}
		
		if(in_array('archives', $_POST['create_page'])) {
			if(!orange_crush_checkForStaticPage('Archives')) {
				orange_crush_createStaticPage('Archives', '', 'archives.php');
			}
		}
		
		if(in_array('tags', $_POST['create_page'])) {
			if(!orange_crush_checkForStaticPage('Tags')) {
				orange_crush_createStaticPage('Tags', '', 'tags.php');
			}
		}
	}
}

function orange_crush_checkForStaticPage($title) {
	global $wpdb, $user_ID;
	get_currentuserinfo();
	
	$query = "SELECT ID FROM $wpdb->posts WHERE post_title='$title' AND post_status='static'";
	$result = $wpdb->query($query);
	
	if($result > 0) {
		return true;
	} else {
		return false;
	}
}

function orange_crush_createStaticPage($post_title, $content, $template) {
	global $wpdb, $user_ID;
	get_currentuserinfo();
	
	$now = current_time('mysql');
	$now_gmt = current_time('mysql', 1);
	$post_author = $user_ID;
	$id_result = $wpdb->get_row("SHOW TABLE STATUS LIKE '$wpdb->posts'");
	$post_ID = $id_result->Auto_increment;
	$post_name = sanitize_title($post_title, $post_ID);
	$ping_status = get_option('default_ping_status');
	$comment_status = get_option('default_comment_status');
	
	$postquery ="INSERT INTO $wpdb->posts (ID, post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt,  post_status, comment_status, ping_status, post_password, post_name, to_ping, post_modified, post_modified_gmt, post_parent, menu_order) VALUES ('$post_ID', '$post_author', '$now', '$now_gmt', '$content', '$post_title', '', 'static', '$comment_status', '$ping_status', '', '$post_name', '', '$now', '$now_gmt', '', '')";
	$result = $wpdb->query($postquery);
	
	$metaquery = "INSERT INTO $wpdb->postmeta(meta_id, post_id, meta_key, meta_value) VALUES('', '$post_ID', '_wp_page_template', '$template')";
	$result2 = $wpdb->query($metaquery);
}

// if we can't find Orange Crush installed lets go ahead and install all the options that run Orange Crush.  This should run only one more time for all our existing users, then they will just be getting the upgrade function if it exists.

if (!get_option('orange_crush_installed')) {
	add_option('orange_crush_installed', $installedVersion, 'This options simply tells us if Orange Crush has been installed before', $autoload);
	add_option('orange_crush_header', 'fish.jpg', '', $autoload);
	add_option('blurb', 'This is the about text', 'Allows you to write a small blurb about you and your blog, which will be put on the frontpage', $autoload);
}

// Here we handle upgrading our users with new options and such.  If orange_crushi_installed is in the DB but the version they are running is lower than our current version, trigger this event.

elseif (get_option('orange_crush_installed') < $installedVersion) {
	if(get_option('orange_crush_installed') < 1.1) {
		add_option('orange_crush_asidescategory', '0', 'ID of a category to display as Asides.');
	}
	update_option('orange_crush_installed', $installedVersion);
}

// This adds the Orange Crush Options page
add_action ('admin_menu', 'orange_crushmenu');

$tloc = '../themes/' . basename(dirname($file)); 

function orange_crushmenu() {
	add_submenu_page('themes.php', 'Orange Crush Options', 'Orange Crush Options', 5, $tloc . 'functions.php', 'menu');
}

function menu() {
	global $installedVersion, $highlightColor;
	
	load_plugin_textdomain('orange_crushoptions');
	// Orange Crush Options page starts here
?>

<?php if (isset($_POST['Submit'])) : ?>
	<div id="updated" class="updated fade">
		<p><?php _e('Orange Crush Options have been updated'); ?></p>
	</div>
<?php endif; ?>

<?php if(get_option('orange_crush_update_notification') == 'true') { ?>
<script src="http://www.anekostudios.com/scripts/oc/version.php?version=<?php echo $installedVersion; ?>" type="text/javascript"></script>
<?php } ?>

<div class="wrap"><h2><?php _e('Orange Crush Options'); ?></h2>
<form name="dofollow" action="" method="post">

	<input type="hidden" name="action" value="<?php orange_crushupdate(); ?>" />
	<input type="hidden" name="page_options" value="'dofollow_timeout'" />
	
	<table width="700" cellspacing="2" cellpadding="5" class="editform">

		<tr valign="top">
			<th scope="row"><?php echo __('Update Notification'); ?></th>
			<td>
				<?php if(get_option('orange_crush_update_notification') == 'true') { ?>
				Orange Crush is set to notify you when an update is available.  <input type="submit" name="orange_crush_update_notification" value="Turn update notification off?" />
				<?php } else { ?>
				Orange Crush can notify you when an update is available.  This involves sending a request to our server, so it is disabled by default.  <input type="submit" name="orange_crush_update_notification" value="Turn update notification on?" />
				<?php } ?>
			</td>
		</tr>

<?php if(!orange_crush_checkForStaticPage('About') || !orange_crush_checkForStaticPage('Archives') || !orange_crush_checkForStaticPage('Tags')) {  } ?>
		
		<tr valign="top">
			<th scope="row"><?php echo __('Alternate Styles'); ?></th>
			<td>
				<label for="alternate_style">
					<?php
					global $wpdb;
					$name = get_option('orange_crush_style');
					
					$style_dir = @ dir(TEMPLATEPATH . '/styles');
					
					if ($style_dir) {
						while(($file = $style_dir->read()) !== false) {
								if (!preg_match('|^\.+$|', $file) && preg_match('@.(css)$@', $file)) 
								$styles[] = $file;
							}
						}
						
						if ($style_dir || $styles) {
							echo "<select name=\"alternate_style\" id=\"alternate_style\">\n";
							echo "<option value=\"$name\">";
							if($name) {
								echo $name;
							} else {
								echo "Default Style";
							}
							echo "</option>\n";
							echo "<option value=\"\">----</option>\n";
							echo "<option value=\"\">Default Style</option>\n";
							$count = 0;
							if($styles) {
								foreach($styles as $style) {
									$count++;
									echo "<option value=\"$style\">$style</option>\n";
								}
							}
							echo "</select>\n";
						}
					?>
				<p><small>Orange Crush lets you choose an alternate style that modifies the default one.  Pick from the list above, or even upload your own to <code>wp-content/themes/<?php echo get_template(); ?>/styles/</code>.</small></p>
				</label>
			</td>
		</tr>


		</table>

	<p class="submit"><input type="submit" name="Submit" value="<?php _e('Update Options') ?> &raquo;" /></p>

</form>
</div>

<?php }

// Orange Crush Options page ends here ?>