<?php

/*
Template Name: DO NOT EDIT

This file is formerly known as "version.php".  
It's necessary for your "updates notification" - if this file
is messed with, then you will not be notified of updates to this theme. 
Do not edit this file.
*/

$currentVersion = "1.162007";
header("Content-type: text/plain");

if($_GET['version'] == $currentVersion) {
echo "document.write('<div class=\"updated\"><p>You have the most recent version of Orange Crush. Your installed version is ${_GET['version']}.</p></div>');";
} else {
echo "document.write('<div class=\"updated\"><p>A new version of the Orange Crush theme is now available. Your installed version is ${_GET['version']}.  If you\'d like to upgrade, please <a href=\"http://www.anekostudios.com/downloads/orange_crush.zip\">click here</a>.</p></div>');";
}

?>